[tool.poetry]
name = "streamlit-example"
version = "0.1.0"
description = ""
authors = ["Amit Kotlovski <amit@amitkot.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
